GET http://127.0.0.1:10001/movies/
Accept: application/json
Authorization:
###

GET http://127.0.0.1:10001/movies/?director_id=12
Accept: application/json
Authorization:
###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json
Authorization:
###

GET http://127.0.0.1:10001/movies/?year=2010
Accept: application/json
Authorization:
###

GET http://127.0.0.1:10001/movies/20
Accept: application/json
Authorization:
###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Authorization: Bearer
Content-Type: application/json

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Authorization: Bearer
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

#PATCH http://127.0.0.1:10001/movies/21
#Accept: application/json
#Authorization: Bearer
#Content-Type: application/json
#
#{
#  "id": 21,
#  "title": "-------",
#  "trailer": "-----",
#  "year": 0,
#  "rating": 0,
#  "description": "0 из 9!",
#  "genre_id": 1,
#  "director_id": 1
#}
#
####

DELETE http://127.0.0.1:10001/movies/21
Accept: application/json
Authorization: Bearer
###

GET http://127.0.0.1:10001/directors/
Accept: application/json
Authorization:
###

POST http://127.0.0.1:10001/directors/
Accept: application/json
Authorization: Bearer
Content-Type: application/json

{
  "name": "Гарри Поттер"
}

###

GET http://127.0.0.1:10001/directors/21
Accept: application/json
Authorization:
###


PUT http://127.0.0.1:10001/directors/21
Accept: application/json
Authorization: Bearer
Content-Type: application/json

{
  "id": 21,
  "name": "Гарри П!"
}

###

DELETE http://127.0.0.1:10001/directors/21
Accept: application/json
Authorization: Bearer
###

GET http://127.0.0.1:10001/genres/
Accept: application/json
Authorization:
###

POST http://127.0.0.1:10001/genres/
Accept: application/json
Authorization: Bearer
Content-Type: application/json

{
  "name": "Жанр Поттер"
}

###

GET http://127.0.0.1:10001/genres/19
Accept: application/json
Authorization:
###

PUT http://127.0.0.1:10001/genres/19
Accept: application/json
Authorization: Bearer
Content-Type: application/json

{
  "id": 19,
  "name": "Жанр П!"
}

###

DELETE http://127.0.0.1:10001/genres/19
Accept: application/json
Authorization: Bearer
###

GET http://127.0.0.1:10001/users/
Accept: application/json
Authorization:
###

POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "Поттер",
  "password": "2512!!**@@",
  "role": "admin"
}

###

GET http://127.0.0.1:10001/users/4
Accept: application/json
Authorization:
###

PUT http://127.0.0.1:10001/users/4
Accept: application/json
Content-Type: application/json

{
  "id": 4,
  "username": "Поттер Гарри",
  "password": "2512!!**@@",
  "role": "user"
}

###

DELETE http://127.0.0.1:10001/users/5
Accept: application/json
###

POST http://127.0.0.1:10001/auth
Accept: application/json
Content-Type: application/json

{
  "username": "Поттер",
  "password": "2512!!**@@"
}

###

PUT http://127.0.0.1:10001/auth
Accept: application/json
Content-Type: application/json

{
  "refresh_token": ""
}

###

